### ISSUE TITLE
Enable Trivy failures in docker action

### ISSUE THREAD

**Issue by MSevey** [celestiaorg/.github#118]
Currently the Trivy check only reports errors it doesn't actually cause the pipeline to fail. 

```[tasklist]
### Tasks
- [ ] Enable on devops branch
- [ ] Test on app and node
- [ ] Fix any errors
- [ ] Push to main, add specific call out in the release notes
- [ ] https://github.com/celestiaorg/.github/pull/119
```

**Comment by MSevey** [comment]
Also remove the VEX warning, REF: https://github.com/celestiaorg/celestia-node/actions/runs/11456093028/job/31873505275

**Comment by smuu** [comment]
we don't want trivy
